---
- name: Stop tomcat
  service: name=tomcat state=stopped

- name: Copy WAR file
  copy: src={{war_file}} dest=/usr/share/tomcat/webapps/{{app_context}}.war

- name: Change ownership of WAR file
  file: path=/usr/share/tomcat/webapps/{{app_context}}.war owner=tomcat group=tomcat state=file

- name: Start tomcat
  service: name=tomcat state=started
